/* eslint-disable new-cap */
import "./globals.css";
import { Antic_Didone } from "next/font/google";

// const pd = Playfair_Display({
//   subsets: ["latin"],
//   display: "swap",
//   variable: "--font-Playfair_Display",
// });

const didot = Antic_Didone({
  subsets: ["latin"],
  display: "swap",
  weight: ["400"],
  variable: "--font-Antic_Didone",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={didot.className}>{children}</body>
    </html>
  );
}
